programPreset = {
    'Menu Ambient': ['https://youtu.be/oyJSV9nnt10'],
    'Town Ambient': ['https://youtu.be/xFjpTF4-PgI', 'https://youtu.be/Y4KX-owEk98'],
    'Forest Ambient': ['https://youtu.be/vXj71r-WrQk', 'https://youtu.be/hBkcwy-iWt8'],
    'Dungeon Ambient': ['https://youtu.be/ki9m6KJ76tU'],
    'Dark Ambient': ['https://youtu.be/WUhMLw6vq8g'],
    'Scary Ambient': ['https://youtu.be/CDWtH8eHeEU'],
    'Heaven Ambient': ['https://youtu.be/RG1ydqEEa0c'],
    'Hell Ambient': ['https://youtu.be/73PGjY_RSA8'],
    'Tavern Ambient': ['https://youtu.be/dd10InDdvJE'],
    'Sea Ambient': ['https://youtu.be/Lyt7enNpwvk'],
    'Beach Ambient': ['https://youtu.be/4W2EfqdOmiI'],
    'Tragic Ambient': ['https://youtu.be/p8UYvbqROdc'],
    'Weak enemies': ['https://youtu.be/cMAALHrANz0'],
    'Average enemies': ['https://youtu.be/pGw2ztHACxA', 'https://youtu.be/fwW6DGYEw88'],
    'Strong enemies': ['https://youtu.be/1OVVTSXVrK4', 'https://youtu.be/e9mfzLW7N6o'],
    'Boss fight': ['https://youtu.be/le1l4eeo8Ow', 'https://youtu.be/NtqRjGP3uoY'],
    'Final Fight': ['https://youtu.be/eE8bk8NJqbE'],
    'Sea Fight': ['https://youtu.be/78k6Wy_c_t0', 'https://youtu.be/BkFXGvwVgmA'],
    'Global War': ['https://youtu.be/0rl7AatkjfA', 'https://youtu.be/EspwQ6Phw0g'],
    'Death of a hero': ['https://youtu.be/qywKyXfswsg'],
    'Evil speech': ['https://youtu.be/q6wDm9C5YEo', 'https://youtu.be/VagES3pxttQ'],
    'fire in the city': ['https://youtu.be/NkstXAUSpyM', 'https://youtu.be/zBY5bVTxOAw'],
    'Genocide': ['https://youtu.be/L5OMYNJ23J4'],
    'Sinking Ship': ['https://youtu.be/p7_lKFPekvc'],
    'Difficult choice': ['https://youtu.be/mB5rsayMxrg']
}
